### ISSUE TITLE
zooming all the way in causes excessive resource usage

### ISSUE THREAD

**Issue by backwardspy** [tinyworldmap/tiny-world-map#1]
at default zoom level:
![image](https://github.com/tinyworldmap/tiny-world-map/assets/289746/51cad21d-1ec4-4b22-b3c2-7e187f3cae4a)

zoomed super far in:
![image](https://github.com/tinyworldmap/tiny-world-map/assets/289746/3a670a7c-70f9-4ce7-a6cb-5de781f3a71f)

memory usage peaks around 5 GB at which point the browser is no longer locked up, but i can't seem to zoom back out anymore.

i also tested it in chromium; the same thing happened but the tab was quickly killed with an out-of-memory error.

**Comment by bopjesvla** [comment]
I can't reproduce this on my computer nor on my phone, but I imagine this is because the country polygon is incredibly large compared to the tile it's drawn on. I've changed the max zoom level to 18 on the landing page, the same as OSM's max zoom level. Does the memory hog occur before that?

**Comment by backwardspy** [comment]
i am still able to replicate it.

as far as i can tell it acts fine right up to a certain point, and then it suddenly starts taking a bunch of CPU time. there's another odd detail i noticed; the memory issue only shows up if i zoom in quickly. if i go slower, one step at a time, then it still hangs when i hit that critical zoom level but it doesn't seem to blow up the memory usage in the same way.

sorry this is all a bit vague, if there's anything i can do to help debug this more effectively let me know.

**Comment by bopjesvla** [comment]
Could you go into your console, and right before the critical zoom level, run `map.getZoom()`? Also, what OS are you using?

**Comment by bopjesvla** [comment]
Also, to test my hypothesis, could you zoom into Russia and Luxembourg and see if you can zoom further into the latter?

**Comment by backwardspy** [comment]
i've just given it another go, and i can no longer zoom in far enough to trigger the issue.
i did try to clear caches etc before testing yesterday, but perhaps i was still on the older version somehow.

**Comment by bopjesvla** [comment]
Oh, I added another safeguard to zooming in. It's good to know that fixes it, thanks for reporting back!
