### ISSUE TITLE
Caspian sea is missing

### ISSUE THREAD

**Issue by havijs** [tinyworldmap/tiny-world-map#2]
I just had a hard time finding my hometown which is along the Caspian sea. I know that Caspian sea is technically a lake, but I think its surface area is big enough to be included on the map.

**Comment by pmarks-net** [comment]
At least include the top 5, so Michigan looks right: https://en.wikipedia.org/wiki/List_of_lakes_by_area

**Comment by bopjesvla** [comment]
Fixed
