### ISSUE TITLE
Zoom level for San Diego

### ISSUE THREAD

**Issue by Keith-S-Thompson** [tinyworldmap/tiny-world-map#3]
I tried the [demo](https://tinyworldmap.com/) and zoomed in on Southern California (I live in San Diego).

I was surprised to see Oceanside (population about 174,000) appear two zoom levels before San Diego (population about 1.4 million)

Looking into the json files, I see that San Diego's zoom level is 8, while Oceanside's is 6.

I suggest that San Diego's zoom level should probably be 6 (the same as San Francisco) or even 5 (the same as San Jose).

I haven't looked for similar issues elsewhere. I'm not suggesting that the zoom level should be based solely on population.

**Comment by bopjesvla** [comment]
The reason this happens is that San Diego is blocked by Tijuana, which is slightly larger, at zoom levels 6-7.
