### ISSUE TITLE
Long city names are squashed regardless of zoom level

### ISSUE THREAD

**Issue by timcastor** [tinyworldmap/tiny-world-map#5]
You can see it for example for Argentina.

![image](https://github.com/tinyworldmap/tiny-world-map/assets/20757080/287fe1ab-adf6-434c-bceb-3345ec7d08d6)

**Comment by bopjesvla** [comment]
We can't let the client compute when to expand labels, so to fix this we'd have to provide extended rendering hints (e.g. don't squash beyond level X). I'm not sure the nature of the project allows for a fix, but I'm open to ideas.

Most of these names must have a shorthand people use in daily life.

**Comment by bopjesvla** [comment]
By using shorthands, the biggest excesses have been fixed in nightly.
