### ISSUE TITLE
Documentation for how can we insert custom cities into the map

### ISSUE THREAD

**Issue by d3n972** [tinyworldmap/tiny-world-map#7]
Currently we can only use the pre-prepared versions of the script. Could you please give some insight on how can we modify the included cities or replace them entirely.

**Comment by bopjesvla** [comment]
Currently, the only way to get a custom map is to hire us. I'd love to document and open-source the code, and make the entire process more reproducable/less dependent on manual changes, but that both takes time and brings in less work, so we'd need an alternative source of funding.
