### ISSUE TITLE
Example images need more than just names

### ISSUE THREAD

**Issue by jidanni** [tinyworldmap/tiny-world-map#9]
Are you sure you want to use
https://github.com/tinyworldmap/tiny-world-map/blob/gh-pages/images/zoomed-in-3.png
in your examples?
People might not browse any further and miss the more lively looking maps further down in the article.

I.e., I would at least show some roads too, not just place names floating on an empty "desert".

**Comment by bopjesvla** [comment]
That's what this is, though. A low-size world map without roads.

**Comment by jidanni** [comment]
Perhaps moves the example area in the image a little to the southwest in order to include some of the coastline at least.

**Comment by bopjesvla** [comment]
That's a good suggestion.
